// app/sveltekit/src/routes/signup/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { enhance } from '$app/forms';
	import { goto } from '$app/navigation';
	import { csrf, getSession, login } from '$lib/session_data';
	/** @type {import('./$types').PageData} */
	export let data;

	let firstName: string;
	let lastName: string;
	let userEmail: string;
	let password: string;
	let confirmPassword: string;
	let isAuthenticated: boolean = false;

	const csrfToken: string | null = data.csrfToken;
	console.log('SignUp page token: ' + csrfToken);

	const validatePassword = () => {
		if (password !== confirmPassword) {
			// Passwords do not match, handle the error
			console.log('Passwords do not match');
			// You can display an error message to the user or perform any other action
		} else {
			// Passwords match, continue with the signup process
			console.log('Passwords match');
			// You can proceed with the signup logic here
		}
	};

	const validateFields = () => {
		if (!firstName || !lastName || !userEmail || !password) {
			// Handle the error when any field is empty
			console.log('Please fill in all fields');
			// You can display an error message to the user or perform any other action
		} else {
			// All fields have values, continue with the signup process
			console.log('All fields have values');
			// You can proceed with the signup logic here
		}
	};

	const signup = async () => {
		try {
			const res = await fetch('/api/signup', {
				method: 'POST',
				credentials: 'same-origin',
				headers: {
					'Content-Type': 'application/json',
					'X-CSRFToken': csrfToken
				},
				body: JSON.stringify({
					firstName,
					lastName,
					userEmail,
					password
				})
			});
			const data = await res.json();
			console.log('Signup data: ' + data.user_email);
		} catch (err) {
			console.log(err);
		}
	};

	// const signup = () => {
	// 	validatePassword();
	// 	validateFields();
	// 	fetch("./api/signup", {
	// 		method: "POST",
	// 		headers: {
	// 			"Content-Type": "application/json",
	// 			"X-CSRFToken": csrfToken
	// 		},
	// 		body: JSON.stringify({
	// 			firstName,
	// 			lastName,
	// 			userEmail,
	// 			password
	// 		})
	// 	})
	// 	.then((res) => {
	// 		console.log("Signup Res: " + res.json())
	// 		// return res.json();
	// 	})
	// 	.then((data) => {
	// 		console.log("Signup Data: " + data.json());
	// 	// 	// login(csrfToken, data.user_email, data.password)
	// 	// 	// .then(authentication => {
	// 	// 	// 	isAuthenticated = authentication
	// 	// 	// });
	// 	})
	// 	.catch((error) => {
	// 		console.log(error);
	// 		// Handle any errors here
	// 	});
	// }
</script>

<div class="flex h-screen w-screen justify-center items-center">
	<div class="flex bg-whisper h-[600px] w-[400px] rounded-xl items-center justify-center">
		<form>
			<div class="flex items-center">
				<h1 class="text-nivaltaBlue font-bold text-xl">Sign Up</h1>
			</div>
			<div class="space-y-12">
				<div class="border-b border-gray-900/10 pb-12">
					<div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
						<div class="sm:col-span-3">
							<label for="first-name" class="block text-sm font-medium leading-6 text-gray-900"
								>First name</label
							>
							<div class="mt-2">
								<input
									type="text"
									name="first-name"
									id="first-name"
									autocomplete="given-name"
									bind:value={firstName}
									class="block w-full rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
								/>
							</div>
						</div>

						<div class="sm:col-span-3">
							<label for="last-name" class="block text-sm font-medium leading-6 text-gray-900"
								>Last name</label
							>
							<div class="mt-2">
								<input
									type="text"
									name="last-name"
									id="last-name"
									autocomplete="family-name"
									bind:value={lastName}
									class="block w-full rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
								/>
							</div>
						</div>

						<div class="sm:col-span-4 lg:col-span-6">
							<label for="email" class="block text-sm font-medium leading-6 text-gray-900"
								>Email address</label
							>
							<div class="mt-2">
								<input
									id="email"
									name="email"
									type="email"
									autocomplete="email"
									bind:value={userEmail}
									class="block w-full rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
								/>
							</div>
						</div>

						<div class="sm:col-span-4 lg:col-span-6">
							<label for="email" class="block text-sm font-medium leading-6 text-gray-900"
								>Password</label
							>
							<div class="mt-2">
								<input
									id="password"
									name="password"
									type="password"
									bind:value={password}
									class="block w-full rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
								/>
							</div>
						</div>

						<div class="sm:col-span-4 lg:col-span-6">
							<label for="email" class="block text-sm font-medium leading-6 text-gray-900"
								>Confirm Password</label
							>
							<div class="mt-2">
								<input
									id="confirmPassword"
									name="confirmPassword"
									type="password"
									bind:value={confirmPassword}
									class="block w-full rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
								/>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="mt-6 flex items-center justify-end gap-x-6">
				<button
					type="button"
					class="text-sm font-semibold leading-6 text-gray-900"
					on:click={() => goto('/login')}>Cancel</button
				>
				<button
					type="button"
					class="rounded-md bg-nivaltaBlue px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
					on:click={() => {
						signup();
						goto('/login');
					}}>Save</button
				>
			</div>
		</form>
	</div>
</div>

// react/src/components/signup/SignupComponent.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../providers/AuthProvider';
import { useCSRF } from '../../providers/CSRFProvider';

const SignupComponent = () => {
  const navigate = useNavigate();
  const { csrfToken } = useCSRF();
  const { login } = useAuth();
  
  const [formData, setFormData] = useState({
    firstName: '',
    lastName: '',
    userEmail: '',
    password: '',
    confirmPassword: ''
  });

  const [formErrors, setFormErrors] = useState({
    password: '',
    fields: ''
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const validateForm = () => {
    let isValid = true;
    const errors = {
      password: '',
      fields: ''
    };

    // Check if any field is empty
    if (!Object.values(formData).every(val => val)) {
      errors.fields = 'Please fill in all fields';
      isValid = false;
    }

    // Check if passwords match
    if (formData.password !== formData.confirmPassword) {
      errors.password = 'Passwords do not match';
      isValid = false;
    }

    setFormErrors(errors);
    return isValid;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    if (!validateForm()) {
      return;
    }

    try {
      // Signup request
      const signupResponse = await fetch('/api/signup', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-CSRFToken': csrfToken
        },
        body: JSON.stringify({
          firstName: formData.firstName,
          lastName: formData.lastName,
          userEmail: formData.userEmail,
          password: formData.password
        })
      });

      if (!signupResponse.ok) {
        throw new Error('Signup failed');
      }

      const signupData = await signupResponse.json();

      // Login after successful signup
      await login({
        userEmail: signupData.userEmail,
        password: formData.password
      });

      navigate('/dashboard');
    } catch (error) {
      console.error('Error during signup:', error);
      setFormErrors(prev => ({
        ...prev,
        fields: 'Failed to create account. Please try again.'
      }));
    }
  };

  return (
    <div className="flex h-screen w-screen justify-center items-center">
      <div className="flex bg-whisper h-[600px] w-[400px] rounded-xl items-center justify-center">
        <form onSubmit={handleSubmit} className="w-full px-8">
          <div className="flex items-center mb-6">
            <h1 className="text-nivaltaBlue font-bold text-xl">Sign Up</h1>
          </div>

          {formErrors.fields && (
            <div className="mb-4 text-red-500 text-sm">
              {formErrors.fields}
            </div>
          )}

          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label htmlFor="firstName" className="block text-sm font-medium text-gray-900">
                  First name
                </label>
                <input
                  type="text"
                  name="firstName"
                  id="firstName"
                  value={formData.firstName}
                  onChange={handleChange}
                  className="block w-full rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm"
                />
              </div>

              <div>
                <label htmlFor="lastName" className="block text-sm font-medium text-gray-900">
                  Last name
                </label>
                <input
                  type="text"
                  name="lastName"
                  id="lastName"
                  value={formData.lastName}
                  onChange={handleChange}
                  className="block w-full rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm"
                />
              </div>
            </div>

            <div>
              <label htmlFor="userEmail" className="block text-sm font-medium text-gray-900">
                Email address
              </label>
              <input
                type="email"
                name="userEmail"
                id="userEmail"
                value={formData.userEmail}
                onChange={handleChange}
                className="block w-full rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm"
              />
            </div>

            <div>
              <label htmlFor="password" className="block text-sm font-medium text-gray-900">
                Password
              </label>
              <input
                type="password"
                name="password"
                id="password"
                value={formData.password}
                onChange={handleChange}
                className="block w-full rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm"
              />
            </div>

            <div>
              <label htmlFor="confirmPassword" className="block text-sm font-medium text-gray-900">
                Confirm Password
              </label>
              <input
                type="password"
                name="confirmPassword"
                id="confirmPassword"
                value={formData.confirmPassword}
                onChange={handleChange}
                className="block w-full rounded-md border-0 py-1.5 px-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm"
              />
              {formErrors.password && (
                <p className="mt-1 text-sm text-red-500">{formErrors.password}</p>
              )}
            </div>
          </div>

          <div className="mt-6 flex items-center justify-end gap-x-6">
            <button
              type="button"
              onClick={() => navigate('/login')}
              className="text-sm font-semibold leading-6 text-gray-900"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="rounded-md bg-nivaltaBlue px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
            >
              Sign up
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default SignupComponent;
