// app/sveltekit/src/lib/components/LoginCard.svelte
<script lang="ts">
	import { callFlaskEndpoint } from '$lib/session_data';
	import { goto } from '$app/navigation';

	let userEmail: string;
	let password: string;

	export let csrfToken: string | null;

	export const login = async () => {
			callFlaskEndpoint(fetch, '/api/login', 'POST',
				{"X-CSRFToken": csrfToken},
				{
					userEmail: userEmail,
					password: password
			}).then((loginResponse) => {
				const isAuthenticated = loginResponse.response_data.login;
				if (isAuthenticated == true) {
					goto('/dashboard');
				}
			}).catch((error) => {
				console.error('Error signing up:', error);
		});
	};

	const handleOAuthLogin = async (provider: string) => {
		try {
			const response = await callFlaskEndpoint(
				fetch,
				`/api/oauth2/authorize/${provider}`,
				'GET',
				{"X-CSRFToken": csrfToken}
			);
			
			if (response.response_data.authorizationUrl) {
				// Redirect to provider's authorization URL
				window.location.href = response.response_data.authorizationUrl;
			}
		} catch (error) {
			console.error(`Error initiating ${provider} OAuth:`, error);
		}
	};	
</script>

<div
	class="flex min-h-full align-middle justify-center flex-col lg:px-4 bg-whisper rounded-lg w-[500px] h-[600px]"
>
	<div class="w-fill items-start">
		<div class="sm:mx-auto sm:w-full sm:max-w-sm">
			<h2 class="mt-10 text-center text-3xl font-bold leading-9 text-nivaltaBlue font-sans">
				Sign in to your account
			</h2>
		</div>

		<div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm w-96 justify-center align-middle">
			<form class="space-y-6">
				<div>
					<div class="mt-2">
						<input
							id="email"
							name="email"
							type="email"
							autocomplete="email"
							placeholder="Email address"
							bind:value={userEmail}
							class="block w-full rounded-md border-0 py-1.5 pl-4 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
							required
						/>
					</div>
				</div>

				<div>
					<div class="mb-2">
						<input
							id="password"
							name="password"
							type="password"
							autocomplete="current-password"
							placeholder="Password"
							bind:value={password}
							class="block pl-4 w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
							required
						/>
					</div>
					<div class="flex items-center justify-between">
						<div class="text-sm">
							<a
								href="/login/forgotpassword"
								class="font-semibold leading-6 text-nivaltaBlue hover:text-indigo-600"
								>Forgot Password</a
							>
						</div>
					</div>
				</div>

				<div>
					<button
						type="button"
						class="flex w-full justify-center rounded-md bg-nivaltaBlue px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
						on:click={login}>Sign In</button
					>
				</div>
			</form>
			<div>
				<div class="mt-10">
					<div class="flex justify-center text-sm font-medium leading-6">
						<span class="bg-whisper px-6 text-gray-900">Or continue with</span>
					</div>
				</div>

				<div class="mt-6 grid grid-cols-2 gap-4">
					<button
						on:click={() => handleOAuthLogin('google')}
						class="flex w-full items-center justify-center gap-3 rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:ring-transparent"
					>
						<svg class="h-5 w-5" viewBox="0 0 24 24" aria-hidden="true">
							<path
								d="M12.0003 4.75C13.7703 4.75 15.3553 5.36002 16.6053 6.54998L20.0303 3.125C17.9502 1.19 15.2353 0 12.0003 0C7.31028 0 3.25527 2.69 1.28027 6.60998L5.27028 9.70498C6.21525 6.86002 8.87028 4.75 12.0003 4.75Z"
								fill="#EA4335"
							/>
							<path
								d="M23.49 12.275C23.49 11.49 23.415 10.73 23.3 10H12V14.51H18.47C18.18 15.99 17.34 17.25 16.08 18.1L19.945 21.1C22.2 19.01 23.49 15.92 23.49 12.275Z"
								fill="#4285F4"
							/>
							<path
								d="M5.26498 14.2949C5.02498 13.5699 4.88501 12.7999 4.88501 11.9999C4.88501 11.1999 5.01998 10.4299 5.26498 9.7049L1.275 6.60986C0.46 8.22986 0 10.0599 0 11.9999C0 13.9399 0.46 15.7699 1.28 17.3899L5.26498 14.2949Z"
								fill="#FBBC05"
							/>
							<path
								d="M12.0004 24.0001C15.2404 24.0001 17.9654 22.935 19.9454 21.095L16.0804 18.095C15.0054 18.82 13.6204 19.245 12.0004 19.245C8.8704 19.245 6.21537 17.135 5.2654 14.29L1.27539 17.385C3.25539 21.31 7.3104 24.0001 12.0004 24.0001Z"
								fill="#34A853"
							/>
						</svg>
						<span class="text-sm font-semibold leading-6">Google</span>
					</button>

					<button
						on:click={() => handleOAuthLogin('github')} 
						class="flex w-full items-center justify-center gap-3 rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:ring-transparent"
					>
						<svg
							class="h-5 w-5 fill-[#24292F]"
							fill="currentColor"
							viewBox="0 0 20 20"
							aria-hidden="true"
						>
							<path
								fill-rule="evenodd"
								d="M10 0C4.477 0 0 4.484 0 10.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0110 4.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.203 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.942.359.31.678.921.678 1.856 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0020 10.017C20 4.484 15.522 0 10 0z"
								clip-rule="evenodd"
							/>
						</svg>
						<span class="text-sm font-semibold leading-6">GitHub</span>
					</button>

					<button
						on:click={() => handleOAuthLogin('azure')}
						class="flex w-full items-center justify-center gap-3 rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:ring-transparent"
					>
						<svg class="h-5 w-5" viewBox="0 0 23 23" aria-hidden="true">
							<path
								d="M12.6196 0.198364L5.75493 5.83254L0.123047 16.3654L3.90867 15.9758L6.33734 11.8468L12.6196 0.198364Z"  
								fill="#F25022"
							/>
							<path 
								d="M12.8648 0.313477L19.73 5.94764L22.9996 16.4805L19.2144 16.0909L16.7852 11.9619L12.8648 0.313477Z"
								fill="#7FBA00"
							/>
							<path
								d="M3.67352 16.3081L6.33734 15.9758L16.5395 16.0909L22.7539 16.4805L16.5395 22.8016H6.33734L3.67352 16.3081Z"
								fill="#00A4EF"
							/>
						</svg>
						<span class="text-sm font-semibold leading-6">Microsoft</span>
					</button>
				</div>
			</div>
			<div class="align-bottom">
				<p class="mt-10 text-center text-sm text-gray-500">
					Not a member?
					<a
						href="/signup"
						class="font-semibold leading-6 text-nivaltaBlue hover:text-indigo-600">Sign up</a
					>
				</p>
			</div>
		</div>
	</div>
</div>

// react/src/components/login/LoginCard.tsx
import React, { useState, FormEvent, ChangeEvent } from 'react';
import { useAuth } from '../../hooks/useAuth';
import { useNavigate } from 'react-router-dom';

interface LoginCredentials {
  email: string;
  password: string;
}

interface OAuthResponse {
  authorizationUrl: string;
}

interface ApiError {
  response?: {
    data?: {
      message?: string;
    };
  };
}

const Login: React.FC = () => {
  const [userEmail, setUserEmail] = useState('');
  const [password, setPassword] = useState('');
  const [formError, setFormError] = useState('');
  const [loading, setLoading] = useState(false);
  const { user, login, oauthLogin } = useAuth();
  const navigate = useNavigate();

  const handleLogin = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setFormError('');
    setLoading(true);
    
    try {
      await login({ email: userEmail, password });
      navigate('/dashboard');
    } catch (err) {
      const error = err as ApiError;
      setFormError(error.response?.data?.message || 'Login failed. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleOAuthLogin = async (provider: string) => {
    try {
      setLoading(true);
      const response = await oauthLogin(provider) as OAuthResponse;
      window.location.href = response.authorizationUrl;
    } catch (err) {
      const error = err as ApiError;
      setFormError(error.response?.data?.message || 'Login failed. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleEmailChange = (e: ChangeEvent<HTMLInputElement>) => {
    setUserEmail(e.target.value);
  };

  const handlePasswordChange = (e: ChangeEvent<HTMLInputElement>) => {
    setPassword(e.target.value);
  };

  return (
    <div className="flex min-h-full align-middle justify-center flex-col lg:px-4 bg-whisper rounded-lg w-[500px] h-[600px]">
      <div className="w-fill items-start">
        <div className="sm:mx-auto sm:w-full sm:max-w-sm">
          <h2 className="mt-10 text-center text-3xl font-bold leading-9 text-nivaltaBlue font-sans">
            Sign in to your account
          </h2>
        </div>

        <div className="mt-10 sm:mx-auto sm:w-full sm:max-w-sm w-96">
          {formError && (
            <div className="mb-4 p-2 text-sm text-red-600 bg-red-100 rounded">
              {formError}
            </div>
          )}

          <div className="mt-10 sm:mx-auto sm:w-full sm:max-w-sm w-96 justify-center align-middle">
            <form className="space-y-6" onSubmit={handleLogin}>
              <div>
                <div className="mt-2">
                  <input
                    id="email"
                    name="email"
                    type="email"
                    autoComplete="email"
                    placeholder="Email address"
                    value={userEmail}
                    onChange={handleEmailChange}
                    className="block w-full rounded-md border-0 py-1.5 pl-4 text-white-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                    required
                  />
                </div>
              </div>

              <div>
                <div className="mb-2">
                  <input
                    id="password"
                    name="password"
                    type="password"
                    autoComplete="current-password"
                    placeholder="Password"
                    value={password}
                    onChange={handlePasswordChange}
                    className="block pl-4 w-full rounded-md border-0 py-1.5 text-white-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                    required
                  />
                </div>
                <div className="flex items-center justify-between">
                  <div className="text-sm">
                    <a
                      href="/login/forgotpassword"
                      className="font-semibold leading-6 text-nivaltaBlue hover:text-indigo-600"
                    >
                      Forgot Password
                    </a>
                  </div>
                </div>
              </div>

              <button
                type="submit"
                disabled={loading}
                className={`flex w-full justify-center rounded-md bg-nivaltaBlue px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 ${
                  loading ? 'opacity-50 cursor-not-allowed' : ''
                }`}
              >
                {loading ? 'Signing in...' : 'Sign In'}
              </button>
            </form>
          </div>

          <div>
            <div className="mt-10">
              <div className="flex justify-center text-sm font-medium leading-6">
                <span className="bg-whisper px-6 text-white-900">Or continue with</span>
              </div>
            </div>

            <div className="mt-6 grid grid-cols-2 gap-4">
              <button
                onClick={() => handleOAuthLogin('google')}
                className="flex w-full items-center justify-center gap-3 rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:ring-transparent"
              >
                <svg className="h-5 w-5" viewBox="0 0 24 24" aria-hidden="true">
                  <path
                    d="M12.0003 4.75C13.7703 4.75 15.3553 5.36002 16.6053 6.54998L20.0303 3.125C17.9502 1.19 15.2353 0 12.0003 0C7.31028 0 3.25527 2.69 1.28027 6.60998L5.27028 9.70498C6.21525 6.86002 8.87028 4.75 12.0003 4.75Z"
                    fill="#EA4335"
                  />
                  <path
                    d="M23.49 12.275C23.49 11.49 23.415 10.73 23.3 10H12V14.51H18.47C18.18 15.99 17.34 17.25 16.08 18.1L19.945 21.1C22.2 19.01 23.49 15.92 23.49 12.275Z"
                    fill="#4285F4"
                  />
                  <path
                    d="M5.26498 14.2949C5.02498 13.5699 4.88501 12.7999 4.88501 11.9999C4.88501 11.1999 5.01998 10.4299 5.26498 9.7049L1.275 6.60986C0.46 8.22986 0 10.0599 0 11.9999C0 13.9399 0.46 15.7699 1.28 17.3899L5.26498 14.2949Z"
                    fill="#FBBC05"
                  />
                  <path
                    d="M12.0004 24.0001C15.2404 24.0001 17.9654 22.935 19.9454 21.095L16.0804 18.095C15.0054 18.82 13.6204 19.245 12.0004 19.245C8.8704 19.245 6.21537 17.135 5.2654 14.29L1.27539 17.385C3.25539 21.31 7.3104 24.0001 12.0004 24.0001Z"
                    fill="#34A853"
                  />
                </svg>
                <span className="text-sm font-semibold leading-6">Google</span>
              </button>

              <button
                onClick={() => handleOAuthLogin('github')}
                className="flex w-full items-center justify-center gap-3 rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:ring-transparent"
              >
                <svg
                  className="h-5 w-5 fill-[#24292F]"
                  fill="currentColor"
                  viewBox="0 0 20 20"
                  aria-hidden="true"
                >
                  <path
                    fillRule="evenodd"
                    d="M10 0C4.477 0 0 4.484 0 10.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0110 4.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.203 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.942.359.31.678.921.678 1.856 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0020 10.017C20 4.484 15.522 0 10 0z"
                    clipRule="evenodd"
                  />
                </svg>
                <span className="text-sm font-semibold leading-6">GitHub</span>
              </button>

              <button
                onClick={() => handleOAuthLogin('azure')}
                className="flex w-full items-center justify-center gap-3 rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus-visible:ring-transparent"
              >
                <svg className="h-5 w-5" viewBox="0 0 23 23" aria-hidden="true">
                  <path
                    d="M12.6196 0.198364L5.75493 5.83254L0.123047 16.3654L3.90867 15.9758L6.33734 11.8468L12.6196 0.198364Z"
                    fill="#F25022"
                  />
                  <path
                    d="M12.8648 0.313477L19.73 5.94764L22.9996 16.4805L19.2144 16.0909L16.7852 11.9619L12.8648 0.313477Z"
                    fill="#7FBA00"
                  />
                  <path
                    d="M3.67352 16.3081L6.33734 15.9758L16.5395 16.0909L22.7539 16.4805L16.5395 22.8016H6.33734L3.67352 16.3081Z"
                    fill="#00A4EF"
                  />
                </svg>
                <span className="text-sm font-semibold leading-6">Microsoft</span>
              </button>
            </div>
          </div>
          <div className="align-bottom">
            <p className="mt-10 text-center text-sm text-gray-500">
              Not a member?{' '}
              <a href="/signup" className="font-semibold leading-6 text-nivaltaBlue hover:text-indigo-600">
                Sign up
              </a>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Login;
